apiVersion: v1
kind: ReplicationController
metadata:
  name: go-api
spec:
  replicas: 3
  selector:
    app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: gadhittana01/goapi:latest
          ports:
            - containerPort: 3000
