apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-api
spec:
  replicas: 3
  selector:
    matchLabels:
      name: go-api
  template:
    metadata:
      name: go-api
      labels:
        name: go-api
    spec:
      containers:
        - name: go-api
          image: gadhittana01/goapi:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  selector:
    name: go-api
  ports:
    - port:       
      targetPort: 3000

---

apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    name: curl
spec:
  containers:
    - name: curl
      image: khannedy/nginx-curl
