apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-api
spec:
  replicas: 3
  selector:
    matchLabels:
      name: go-api
  template:
    metadata:
      name: go-api
      labels:
        name: go-api
    spec:
      containers:
        - name: go-api
          image: gadhittana01/goapi:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  type: LoadBalancer
  selector:
    name: go-api
  ports:
    - port: 3000
      targetPort: 3000
