apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-world-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-world-rest-api
  template:
    metadata:
      name: hello-world-rest-api
      labels:
        name: hello-world-rest-api
    spec:
      containers:
        - name: hello-world-rest-api
          image: in28min/hello-world-rest-api:0.0.1.RELEASE
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-rest-api-service
spec:
  selector:
    name: hello-world-rest-api
  ports:
    - port: 8080
      targetPort: 8080

